# Generated by Django 5.2.3 on 2025-06-23 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_membership_unique_together_membership_role_and_more'),
        ('assessments', '0001_initial'),
        ('vendors', '0003_vendortrustprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=50)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='vendors.vendor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assessment',
            name='solution',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='assessments.solution'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('organization', 'solution', 'questionnaire')},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='vendor',
        ),
    ]
