# Generated by Django 5.2.3 on 2025-06-23 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_solution_alter_assessment_unique_together_and_more'),
        ('vendors', '0004_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='solution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='vendors.solution'),
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
