# Generated by Django 5.2.3 on 2025-07-16 00:58

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_assessment_score_assessment_information_value_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='supporting_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partially'), ('n/a', 'Not Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('severe', 'Severe'), ('undetermined', 'Undetermined')], default='undetermined', help_text='Risk level decided after manual review or tagging', max_length=20),
        ),
    ]
