# Generated by Django 5.2.3 on 2025-06-23 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_assessment_solution_delete_solution'),
        ('vendors', '0006_remove_vendortrustprofile_gdpr_compliant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='vendors.solution'),
        ),
    ]
