# Generated by Django 5.2.3 on 2025-07-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_answer_supporting_text_questionnaire_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_nist_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
