# Generated by Django 5.2.3 on 2025-07-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_questionnairequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='recommended_risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('severe', 'Severe'), ('undetermined', 'Undetermined')], default='undetermined', help_text='Risk level recommended by artifacts', max_length=20),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question',
            field=models.ManyToManyField(related_name='questionnaires', through='assessments.QuestionnaireQuestion', to='assessments.question'),
        ),
    ]
