# Generated by Django 5.2.3 on 2025-07-27 23:59

import trust.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_assessment_recommended_risk_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='artifact',
            field=models.FileField(blank=True, help_text='Optional: Upload certification file', null=True, upload_to=trust.utils.cert_artifact_path),
        ),
    ]
