# Generated by Django 5.2.3 on 2025-08-29 08:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_authevent_event'),
        ('thirdparties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyTrustProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score', models.PositiveIntegerField(default=0, help_text='VendorGuard Trust Index (0–1000).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('notes', models.TextField(blank=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='archived',
            field=models.BooleanField(default=False, help_text='Soft-delete flag used by archive actions and list filters.'),
        ),
        migrations.AddField(
            model_name='thirdpartyservice',
            name='archived',
            field=models.BooleanField(default=False, help_text='Soft-delete flag used by archive actions and list filters.'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='dpia_required',
            field=models.BooleanField(default=False, help_text='Set when personal data processing requires a DPIA under your policy.'),
        ),
        migrations.AlterField(
            model_name='thirdpartyevidence',
            name='url',
            field=models.URLField(blank=True, help_text='Link to externally stored evidence.'),
        ),
        migrations.AddIndex(
            model_name='thirdparty',
            index=models.Index(fields=['archived'], name='thirdpartie_archive_0cc4b3_idx'),
        ),
        migrations.AddIndex(
            model_name='thirdpartyservice',
            index=models.Index(fields=['archived'], name='thirdpartie_archive_ffff13_idx'),
        ),
        migrations.AddField(
            model_name='thirdpartytrustprofile',
            name='third_party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to='thirdparties.thirdparty'),
        ),
        migrations.AddIndex(
            model_name='thirdpartytrustprofile',
            index=models.Index(fields=['trust_score'], name='thirdpartie_trust_s_306574_idx'),
        ),
        migrations.AddIndex(
            model_name='thirdpartytrustprofile',
            index=models.Index(fields=['archived'], name='thirdpartie_archive_c89822_idx'),
        ),
    ]
