# Generated by Django 5.2.3 on 2025-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdparties', '0002_thirdpartytrustprofile_thirdparty_archived_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thirdpartyservice',
            options={'ordering': ['third_party__name', 'name'], 'verbose_name': 'Third Party Solution', 'verbose_name_plural': 'Third Party Solutions'},
        ),
        migrations.AlterField(
            model_name='thirdpartyservice',
            name='service_type',
            field=models.CharField(choices=[('saas', 'SaaS'), ('paas', 'PaaS'), ('iaas', 'IaaS'), ('msp', 'Managed Service'), ('consulting', 'Consulting'), ('other', 'Other')], default='saas', max_length=20, verbose_name='Solution Type'),
        ),
    ]
