# assessments/constants.py

# Certification Types
CERT_TYPE_GDPR = "GDPR"
CERT_TYPE_ISO_27001 = "ISO_27001"
CERT_TYPE_SOC2 = "SOC2"
CERT_TYPE_PCI_DSS = "PCI_DSS"
CERT_TYPE_IRAP = "IRAP"

CERTIFICATION_TYPE_CHOICES = [
    (CERT_TYPE_GDPR, "GDPR"),
    (CERT_TYPE_ISO_27001, "ISO 27001"),
    (CERT_TYPE_SOC2, "SOC 2 Type 2"),
    (CERT_TYPE_PCI_DSS, "PCI DSS"),
    (CERT_TYPE_IRAP, "IRAP"),
]
