# Generated by Django 5.2.3 on 2025-06-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='role',
        ),
    ]
