# Generated by Django 5.2.3 on 2025-08-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_authevent_emailverificationtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='event',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_reset', 'Password Reset'), ('email_verified', 'Email Verified')], max_length=32),
        ),
    ]
