# Generated by Django 5.2.3 on 2025-06-27 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='VendorOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('offering_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('integration', 'Integration')], default='product', max_length=50)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorTrustProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_cyber_insurance', models.BooleanField(default=False)),
                ('has_data_breach', models.BooleanField(default=False)),
                ('last_breach_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('trust_score', models.IntegerField(default=0, help_text='0–100 score based on trust attributes')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to='vendors.vendor')),
            ],
        ),
    ]
