# Generated by Django 5.2.3 on 2025-06-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoroffering',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
