# Generated by Django 5.2.3 on 2025-06-23 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTrustProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdpr_compliant', models.BooleanField(default=False)),
                ('iso_27001_certified', models.BooleanField(default=False)),
                ('soc_2_type_2_certified', models.BooleanField(default=False)),
                ('has_cyber_insurance', models.BooleanField(default=False)),
                ('last_breach_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('trust_score', models.IntegerField(default=0, help_text='0–100 score based on trust attributes')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to='vendors.vendor')),
            ],
        ),
    ]
