# Generated by Django 5.2.3 on 2025-07-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendoroffering_risk_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoroffering',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
