# Generated by Django 5.2.3 on 2025-07-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_updated_by_vendoroffering_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendortrustprofile',
            name='trust_score',
            field=models.IntegerField(default=0, help_text='Score calculated based on trust signals (0–100)'),
        ),
    ]
