# Generated by Django 5.2.3 on 2025-06-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortrustprofile',
            name='has_data_breach',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('integration', 'Integration')], default='product', max_length=50),
        ),
    ]
