# Generated by Django 5.2.3 on 2025-06-23 07:23

import django.db.models.deletion
import vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendortrustprofile_has_data_breach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendortrustprofile',
            name='gdpr_compliant',
        ),
        migrations.RemoveField(
            model_name='vendortrustprofile',
            name='iso_27001_certified',
        ),
        migrations.RemoveField(
            model_name='vendortrustprofile',
            name='soc_2_type_2_certified',
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GDPR', 'GDPR'), ('ISO_27001', 'ISO 27001'), ('SOC2', 'SOC 2 Type 2'), ('PCI_DSS', 'PCI DSS'), ('IRAP', 'IRAP')], max_length=50)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cert_number', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('artifact', models.FileField(blank=True, help_text='Optional: Upload certification file', null=True, upload_to=vendors.models.cert_artifact_path)),
                ('external_url', models.URLField(blank=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='vendors.vendor')),
            ],
        ),
    ]
