# Generated by Django 5.2.3 on 2025-07-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendortrustprofile_trust_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoroffering',
            old_name='risk_score',
            new_name='latest_risk_score',
        ),
        migrations.AddField(
            model_name='vendoroffering',
            name='data_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendoroffering',
            name='data_types_handled',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendoroffering',
            name='hosting_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendoroffering',
            name='hosting_type',
            field=models.CharField(blank=True, choices=[('cloud', 'Cloud'), ('on_premise', 'On-Premise'), ('hybrid', 'Hybrid')], max_length=50),
        ),
        migrations.AddField(
            model_name='vendoroffering',
            name='processes_pii',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendoroffering',
            name='stores_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendoroffering',
            name='transmits_data',
            field=models.BooleanField(default=False),
        ),
    ]
