# Generated by Django 5.2.3 on 2025-06-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_remove_vendortrustprofile_gdpr_compliant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='industry',
            field=models.CharField(default='ABC', max_length=255),
            preserve_default=False,
        ),
    ]
