# Generated by Django 5.2.3 on 2025-07-29 23:59

import django.contrib.postgres.fields
from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


def clean_array_field(apps, schema_editor):
    VendorOffering = apps.get_model("vendors", "VendorOffering")
    VendorOffering.objects.filter(data_types_handled="").update(data_types_handled=[])


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0006_previous_migration"),
    ]

    operations = [
        migrations.RunPython(clean_array_field),
        migrations.AlterField(
            model_name="vendoroffering",
            name="data_types_handled",
            field=ArrayField(...),
        ),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0006_rename_risk_score_vendoroffering_latest_risk_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendoroffering",
            name="data_types_handled",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("pii", "Personally Identifiable Information"),
                        ("phi", "Protected Health Information"),
                        ("pci", "Payment Card Information"),
                        ("financial", "Financial Records"),
                        ("business", "General Business Data"),
                        ("credentials", "Credentials / Passwords"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
