# Generated by Django 5.2.3 on 2025-07-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('vendors', '0007_alter_vendoroffering_data_types_handled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoroffering',
            name='data_types_handled',
        ),
        migrations.AddField(
            model_name='vendoroffering',
            name='data_types_handled',
            field=models.ManyToManyField(blank=True, to='common.datatype'),
        ),
    ]
