# Generated by Django 5.2.3 on 2025-08-11 07:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_authevent_emailverificationtoken_and_more'),
        ('vendors', '0008_remove_vendoroffering_data_types_handled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['vendor__name', '-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('soc2', 'SOC 2'), ('iso27001', 'ISO 27001'), ('pentest', 'Penetration Test'), ('sig', 'SIG Questionnaire'), ('caiq', 'CAIQ'), ('dpa', 'Data Processing Agreement'), ('contract', 'Contract'), ('dpia', 'DPIA'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, help_text='Link to externally stored evidence.')),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expires_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['vendor__name', 'doc_type', '-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=191)),
            ],
            options={
                'ordering': ['vendor__name', 'domain'],
            },
        ),
        migrations.RemoveField(
            model_name='vendortrustprofile',
            name='vendor',
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vendoroffering',
            options={'ordering': ['vendor__name', 'name']},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='vendoroffering',
            unique_together={('vendor', 'name')},
        ),
        migrations.AddField(
            model_name='vendor',
            name='criticality',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='dpia_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_assessed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='next_review_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='processes_pci',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='processes_phi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='processes_pii',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='risk_rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–100 snapshot score.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='security_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='security_portal_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Tier 1 – Critical'), (2, 'Tier 2 – Important'), (3, 'Tier 3 – Standard')], default=3),
        ),
        migrations.AddField(
            model_name='vendoroffering',
            name='data_classification',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='confidential', help_text='Highest classification handled by this offering.', max_length=20),
        ),
        migrations.AddField(
            model_name='vendoroffering',
            name='processes_pci',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendoroffering',
            name='processes_phi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendoroffering',
            name='service_type',
            field=models.CharField(choices=[('saas', 'SaaS'), ('paas', 'PaaS'), ('iaas', 'IaaS'), ('msp', 'Managed Service'), ('consulting', 'Consulting'), ('other', 'Other')], default='saas', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendoroffering',
            name='processes_pii',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['organization', 'name'], name='vendors_ven_organiz_9a395a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['status'], name='vendors_ven_status_2dcb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['tier'], name='vendors_ven_tier_845a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['criticality'], name='vendors_ven_critica_cdb350_idx'),
        ),
        migrations.AddIndex(
            model_name='vendoroffering',
            index=models.Index(fields=['vendor', 'name'], name='vendors_ven_vendor__08a98c_idx'),
        ),
        migrations.AddIndex(
            model_name='vendoroffering',
            index=models.Index(fields=['service_type'], name='vendors_ven_service_609f6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_vendor_name_per_org'),
        ),
        migrations.AddField(
            model_name='vendorcontact',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='vendordomain',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='vendors.vendor'),
        ),
        migrations.DeleteModel(
            name='VendorTrustProfile',
        ),
        migrations.RemoveField(
            model_name='vendoroffering',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='vendoroffering',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendoroffering',
            name='data_location',
        ),
        migrations.RemoveField(
            model_name='vendoroffering',
            name='data_types_handled',
        ),
        migrations.RemoveField(
            model_name='vendoroffering',
            name='hosting_provider',
        ),
        migrations.RemoveField(
            model_name='vendoroffering',
            name='hosting_type',
        ),
        migrations.RemoveField(
            model_name='vendoroffering',
            name='latest_risk_score',
        ),
        migrations.RemoveField(
            model_name='vendoroffering',
            name='offering_type',
        ),
        migrations.RemoveField(
            model_name='vendoroffering',
            name='stores_data',
        ),
        migrations.RemoveField(
            model_name='vendoroffering',
            name='transmits_data',
        ),
        migrations.RemoveField(
            model_name='vendoroffering',
            name='updated_by',
        ),
        migrations.AddIndex(
            model_name='vendorcontact',
            index=models.Index(fields=['vendor', 'email'], name='vendors_ven_vendor__202e6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorcontact',
            constraint=models.UniqueConstraint(fields=('vendor', 'email'), name='uniq_contact_email_per_vendor'),
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['vendor', 'doc_type'], name='vendors_ven_vendor__d42708_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordomain',
            index=models.Index(fields=['vendor', 'domain'], name='vendors_ven_vendor__1fe000_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendordomain',
            constraint=models.UniqueConstraint(fields=('vendor', 'domain'), name='uniq_domain_per_vendor'),
        ),
    ]
