# Generated by Django 5.2.3 on 2025-08-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_vendorcontact_vendordocument_vendordomain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'permissions': [('can_submit', 'Can submit vendor for approval'), ('can_request_changes', 'Can request changes on vendor'), ('can_reject', 'Can reject vendor'), ('can_complete', 'Can mark vendor as complete')]},
        ),
        migrations.AddField(
            model_name='vendor',
            name='tenant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(default='DRAFT', max_length=50),
        ),
    ]
