# Generated by Django 5.2.3 on 2025-08-29 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_authevent_event'),
        ('vendors', '0010_alter_vendor_options_vendor_tenant_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vendor',
            name='vendors_ven_status_2dcb2a_idx',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='status',
            new_name='wf_state',
        ),
        migrations.AddField(
            model_name='vendor',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['wf_state'], name='vendors_ven_wf_stat_f2db7e_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['archived'], name='vendors_ven_archive_c8af5f_idx'),
        ),
    ]
